services:
  - type: web
    name: amrn-api
    runtime: python
    rootDir: amr-hgt-tool/backend
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT --timeout 300 app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
